/obj/structure/retail/clothing_store
	desc = "Лучшие наряды в городе... если зарплаты хватит, работяга."
	products_list = list(
		new /datum/data/vending_product("Алое платье", /obj/item/clothing/under/vampire/primogen_toreador/female	,	350),
		new /datum/data/vending_product("Чёрное платье", /obj/item/clothing/under/vampire/business,	250),
		new /datum/data/vending_product("Чёрное вечернее платье", /obj/item/clothing/under/vampire/gown_black,	250),
		new /datum/data/vending_product("Белое вечернее платье", /obj/item/clothing/under/vampire/gown_white,	250),
		new /datum/data/vending_product("Чёрная шаль", /obj/item/clothing/suit/vampire/shawl_black,	250),
		new /datum/data/vending_product("Белая шаль", /obj/item/clothing/suit/vampire/shawl_white,	250),
		new /datum/data/vending_product("Кожаные штаны", /obj/item/clothing/under/vampire/leatherpants,	200),
		new /datum/data/vending_product("Нарядный серый костюм", /obj/item/clothing/under/vampire/fancy_gray,	150),
		new /datum/data/vending_product("Нарядный красный костюм", /obj/item/clothing/under/vampire/fancy_red,	150),
		new /datum/data/vending_product("Чёрный дорогой костюм", /obj/item/clothing/under/vampire/ventrue,	50),
		new /datum/data/vending_product("Чёрный дорогой костюм с юбкой", /obj/item/clothing/under/vampire/ventrue/female,	50),
		new /datum/data/vending_product("Белый деловой костюм", /obj/item/clothing/under/vampire/office,	50),
		new /datum/data/vending_product("Чёрное пальто с костюмом", /obj/item/clothing/under/vampire/rich,	45),
		new /datum/data/vending_product("Бордовый костюм", /obj/item/clothing/under/vampire/tremere,	35),
		new /datum/data/vending_product("Бордовый костюм с юбкой", /obj/item/clothing/under/vampire/tremere/female,	35),
		new /datum/data/vending_product("Простой чёрный костюм",	 /obj/item/clothing/under/vampire/suit,	50),
		new /datum/data/vending_product("Простой чёрный костюм с юбкой",	 /obj/item/clothing/under/vampire/suit/female,	50),
		new /datum/data/vending_product("Простой красный костюм",	 /obj/item/clothing/under/vampire/sheriff,	80),
		new /datum/data/vending_product("Простой красный костюм с юбкой",	 /obj/item/clothing/under/vampire/sheriff/female,	80),
		new /datum/data/vending_product("Простой синий костюм",	 /obj/item/clothing/under/vampire/clerk,	90),
		new /datum/data/vending_product("Простой синий костюм с юбкой",	 /obj/item/clothing/under/vampire/clerk/female,	90),
		new /datum/data/vending_product("Коричневый костюм",	 /obj/item/clothing/under/vampire/archivist,	60),
		new /datum/data/vending_product("Коричневый костюм с юбкой",	 /obj/item/clothing/under/vampire/archivist/female,	60),
		new /datum/data/vending_product("Экстравагантный наряд", /obj/item/clothing/under/vampire/toreador,	30),
		new /datum/data/vending_product("Женский экстравагантный наряд", /obj/item/clothing/under/vampire/toreador/female,	30),
		new /datum/data/vending_product("Чёрно-фиолетовый наряд", /obj/item/clothing/under/vampire/sexy,	25),
		new /datum/data/vending_product("Пижонский пиджак", /obj/item/clothing/under/vampire/slickback, 25),
		new /datum/data/vending_product("Классический бомбер", /obj/item/clothing/suit/vampire/bomber_jacket_classic,	90),
		new /datum/data/vending_product("Серый бомбер", /obj/item/clothing/suit/vampire/bomber_jacket_gray,	90),
		new /datum/data/vending_product("Спортивный костюм", /obj/item/clothing/under/vampire/sport,	25),
		new /datum/data/vending_product("Замызганные штаны", /obj/item/clothing/under/vampire/malkavian,	20),
		new /datum/data/vending_product("Странный наряд готичной школьницы", /obj/item/clothing/under/vampire/malkavian/female,	20),
		new /datum/data/vending_product("Готическая одежда", /obj/item/clothing/under/vampire/gothic,	20),
		new /datum/data/vending_product("Готический наряд", /obj/item/clothing/under/vampire/brujah,	20),
		new /datum/data/vending_product("Женский панк-наряд", /obj/item/clothing/under/vampire/brujah/female,	20),
		new /datum/data/vending_product("Рубашка с пентаграммой", /obj/item/clothing/under/vampire/baali,	20),
		new /datum/data/vending_product("Юбка с пентаграммой", /obj/item/clothing/under/vampire/baali/female,	20),
		new /datum/data/vending_product("Панк-наряд", /obj/item/clothing/under/vampire/emo,	20),
		new /datum/data/vending_product("Красный хипстерский наряд", /obj/item/clothing/under/vampire/red,	20),
		new /datum/data/vending_product("Мятая рубашка", /obj/item/clothing/under/vampire/bouncer,	15),
		new /datum/data/vending_product("Синий комбинезон", /obj/item/clothing/under/vampire/mechanic,	20),
		new /datum/data/vending_product("Чёрный комбинезон", /obj/item/clothing/under/vampire/graveyard, 20),
		new /datum/data/vending_product("Чёрный гранжевый наряд", /obj/item/clothing/under/vampire/black,	20),
		new /datum/data/vending_product("Латексный костюм", /obj/item/clothing/under/vampire/nosferatu,	15),
		new /datum/data/vending_product("Женский латексный костюм", /obj/item/clothing/under/vampire/nosferatu/female,	15),
		new /datum/data/vending_product("Походная одежда", /obj/item/clothing/under/vampire/gangrel,	15),
		new /datum/data/vending_product("Женская походная одежда", /obj/item/clothing/under/vampire/gangrel/female,	15),
		new /datum/data/vending_product("Жёлтая майка", /obj/item/clothing/under/vampire/larry,	15),
		new /datum/data/vending_product("Белая майка", /obj/item/clothing/under/vampire/bandit,	15),
		new /datum/data/vending_product("Белая водолазка", /obj/item/clothing/under/vampire/turtleneck_white,	15),
		new /datum/data/vending_product("Чёрная водолазка", /obj/item/clothing/under/vampire/turtleneck_black,	15),
		new /datum/data/vending_product("Красная водолазка", /obj/item/clothing/under/vampire/turtleneck_red,	15),
		new /datum/data/vending_product("Тёмно-синяя водолазка", /obj/item/clothing/under/vampire/turtleneck_navy,	15),
		new /datum/data/vending_product("Байкерский наряд", /obj/item/clothing/under/vampire/biker,	15),
		new /datum/data/vending_product("Наряд для бурлеска", /obj/item/clothing/under/vampire/burlesque,	15),
		new /datum/data/vending_product("Джинсовые мини-шорты", /obj/item/clothing/under/vampire/burlesque/daisyd,	10),
		new /datum/data/vending_product("Чёрные туфли", /obj/item/clothing/shoes/vampire,	10),
		new /datum/data/vending_product("Коричневые туфли", /obj/item/clothing/shoes/vampire/brown,	10),
		new /datum/data/vending_product("Белые туфли", /obj/item/clothing/shoes/vampire/white,	10),
		new /datum/data/vending_product("Чёрные ботинки", /obj/item/clothing/shoes/vampire/jackboots,	10),
		new /datum/data/vending_product("Рабочие ботинки", /obj/item/clothing/shoes/vampire/jackboots/work,	10),
		new /datum/data/vending_product("Кроссовки", /obj/item/clothing/shoes/vampire/sneakers,	10),
		new /datum/data/vending_product("Красные кроссовки", /obj/item/clothing/shoes/vampire/sneakers/red,	10),
		new /datum/data/vending_product("Туфли на каблуках", /obj/item/clothing/shoes/vampire/heels,	35),
		new /datum/data/vending_product("Красные туфли на каблуках", /obj/item/clothing/shoes/vampire/heels/red,	35),
		new /datum/data/vending_product("Туфли из змеиной кожи", /obj/item/clothing/shoes/vampire/businessscaly,	35),
		new /datum/data/vending_product("Чёрные туфли", /obj/item/clothing/shoes/vampire/businessblack,	35),
		new /datum/data/vending_product("Туфли с металлическим носком", /obj/item/clothing/shoes/vampire/businesstip,	50),
		new /datum/data/vending_product("Фиолетовая шуба", /obj/item/clothing/suit/vampire/slickbackcoat,	500),
		new /datum/data/vending_product("Чересчур пафосный пиджак", /obj/item/clothing/suit/vampire/majima_jacket,	100),
		new /datum/data/vending_product("Лабораторный халат", /obj/item/clothing/suit/vampire/labcoat,	75),
		new /datum/data/vending_product("Нарядный серый пиджак", /obj/item/clothing/suit/vampire/fancy_gray,	50),
		new /datum/data/vending_product("Нарядный красный пиджак", /obj/item/clothing/suit/vampire/fancy_red,	50),
		new /datum/data/vending_product("Чёрный плащ", /obj/item/clothing/suit/vampire/trench,	45),
		new /datum/data/vending_product("Коричневый плащ", /obj/item/clothing/suit/vampire/trench/alt,	35),
		new /datum/data/vending_product("Коричневая куртка", /obj/item/clothing/suit/vampire/coat,	15),
		new /datum/data/vending_product("Зелёная куртка", /obj/item/clothing/suit/vampire/coat/alt,	15),
		new /datum/data/vending_product("Куртка", /obj/item/clothing/suit/vampire/jacket,	15),
		new /datum/data/vending_product("Красная куртка", /obj/item/clothing/suit/vampire/jacket/red, 15),
		new /datum/data/vending_product("Укороченная чёрная куртка", /obj/item/clothing/suit/vampire/jacket/cropped, 15),
		new /datum/data/vending_product("Укороченная красная куртка", /obj/item/clothing/suit/vampire/jacket/cropped/red, 15),
		new /datum/data/vending_product("Чёрное пальто", /obj/item/clothing/suit/vampire/coat/winter,	15),
		new /datum/data/vending_product("Красное пальто", /obj/item/clothing/suit/vampire/coat/winter/alt,	15),
		new /datum/data/vending_product("Жёлтые авиаторы", /obj/item/clothing/glasses/vampire/yellow,	20),
		new /datum/data/vending_product("Красные авиаторы", /obj/item/clothing/glasses/vampire/red,	20),
		new /datum/data/vending_product("Тёмные очки", /obj/item/clothing/glasses/vampire/sun,	20),
		new /datum/data/vending_product("Очки с диоптриями", /obj/item/clothing/glasses/vampire/perception,	20),
		new /datum/data/vending_product("Кожаные перчатки", /obj/item/clothing/gloves/vampire/leather,	25),
		new /datum/data/vending_product("Резиновые перчатки", /obj/item/clothing/gloves/vampire/cleaning,	15),
		new /datum/data/vending_product("Латексные перчатки", /obj/item/clothing/gloves/vampire/latex,	5),
		new /datum/data/vending_product("Чёрные рабочие перчатки", /obj/item/clothing/gloves/vampire/work,	45),
		// CRIMSON EDIT ADD START
		new /datum/data/vending_product("Тёмные очки", /obj/item/clothing/glasses/sunglasses,	25),
		new /datum/data/vending_product("Нуарные тёмные очки", /obj/item/clothing/glasses/sunglasses/noir,	30),
		new /datum/data/vending_product("Чёрные остроугольные очки", /obj/item/clothing/glasses/sunglasses/gar,	85),
		// CRIMSON EDIT ADD END
		new /datum/data/vending_product("Бандана", /obj/item/clothing/head/vampire/bandana,	10),
		new /datum/data/vending_product("Красная бандана", /obj/item/clothing/head/vampire/bandana/red,	10),
		new /datum/data/vending_product("Чёрная бандана", /obj/item/clothing/head/vampire/bandana/black,	10),
		new /datum/data/vending_product("Бейсболка", /obj/item/clothing/head/vampire/baseballcap, 10),
		new /datum/data/vending_product("Ушанка", /obj/item/clothing/head/vampire/ushanka, 20),
		new /datum/data/vending_product("Вязаная шапка", /obj/item/clothing/head/vampire/beanie,	10),
		new /datum/data/vending_product("Чёрная вязаная шапка", /obj/item/clothing/head/vampire/beanie/black,	10),
		new /datum/data/vending_product("Потрёпанная вязаная шапка", /obj/item/clothing/head/vampire/beanie/homeless,	10),
		new /datum/data/vending_product("Шарф", /obj/item/clothing/neck/vampire/scarf,	10),
		new /datum/data/vending_product("Красный шарф", /obj/item/clothing/neck/vampire/scarf/red,	10),
		new /datum/data/vending_product("Синий шарф", /obj/item/clothing/neck/vampire/scarf/blue,	10),
		new /datum/data/vending_product("Зелёный шарф", /obj/item/clothing/neck/vampire/scarf/green,	10),
		new /datum/data/vending_product("Белый шарф", /obj/item/clothing/neck/vampire/scarf/white,	10),
		new /datum/data/vending_product("Золотой крест", /obj/item/card/hunter, 30),
		new /datum/data/vending_product("Серебряный крест", /obj/item/card/hunter/silver, 25),
		new /datum/data/vending_product("Спортивная сумка", /obj/item/storage/backpack/duffelbag,	100),
		new /datum/data/vending_product("Рюкзак", /obj/item/storage/backpack, 100),
		new /datum/data/vending_product("Сумка через плечо", /obj/item/storage/backpack/satchel, 100),
		new /datum/data/vending_product("Кожаная сумка через плечо", /obj/item/storage/backpack/satchel/leather, 150),
// CRIMSON EDIT ADD START - Shop Inventories Additions
		new /datum/data/vending_product("Бумажник", /obj/item/storage/wallet/darkpack, 25),
		new /datum/data/vending_product("Ткань", /obj/item/stack/sheet/cloth, 5),
		new /datum/data/vending_product("Мешковатая одежда", /obj/item/clothing/under/vampire/pinkman, 15),
		new /datum/data/vending_product("Синяя мешковатая одежда", /obj/item/clothing/under/vampire/pinkman/blue, 15),
		new /datum/data/vending_product("Белая мешковатая одежда", /obj/item/clothing/under/vampire/pinkman/white, 15),
		new /datum/data/vending_product("Коричневая мешковатая одежда", /obj/item/clothing/under/vampire/pinkman/brown, 15),
		new /datum/data/vending_product("Серые джинсы клёш", /obj/item/clothing/under/vampire/bootcut_jeans, 15),
		new /datum/data/vending_product("Варёные джинсы клёш", /obj/item/clothing/under/vampire/bootcut_jeans/stonewashed, 15),
		new /datum/data/vending_product("Синие джинсы клёш", /obj/item/clothing/under/vampire/bootcut_jeans/blue, 15),
		new /datum/data/vending_product("Серые широкие джинсы с цепями", /obj/item/clothing/under/vampire/tripp_jeans, 15),
		new /datum/data/vending_product("Синие широкие джинсы с цепями", /obj/item/clothing/under/vampire/tripp_jeans/blue, 15),
		new /datum/data/vending_product("Красные широкие джинсы с цепями", /obj/item/clothing/under/vampire/tripp_jeans/red, 15),
		new /datum/data/vending_product("Бомбер", /obj/item/clothing/suit/vampire/toggled/bomber_jacket, 25),
		new /datum/data/vending_product("Бомбер наизнанку", /obj/item/clothing/suit/vampire/toggled/bomber_jacket/inverted, 25),
		new /datum/data/vending_product("Простая коричневая куртка", /obj/item/clothing/suit/vampire/toggled/plain_jacket, 20),
		new /datum/data/vending_product("Простая чёрная куртка", /obj/item/clothing/suit/vampire/toggled/plain_jacket/black, 20),
		new /datum/data/vending_product("Армейская куртка", /obj/item/clothing/suit/vampire/toggled/military_jacket, 25),
		new /datum/data/vending_product("Сапоги с пряжками", /obj/item/clothing/shoes/vampire/harness_boots, 30),
		new /datum/data/vending_product("Коричневые сапоги с пряжками", /obj/item/clothing/shoes/vampire/harness_boots/brown, 30),

// CRIMSON EDIT ADD END - Shop Inventories Additions
	)
