/obj/structure/retail/costume_store
	desc = "Подберите маску и спрячьте наконец эту рожу."
	products_list = list(
		new /datum/data/vending_product("Балаклава", /obj/item/clothing/mask/vampire/balaclava, 10),
		new /datum/data/vending_product("Шарф на лицо", /obj/item/clothing/mask/facescarf/vampire, 10),
		new /datum/data/vending_product("Бандана", /obj/item/clothing/mask/bandana/vampire, 10),
		new /datum/data/vending_product("Полосатая бандана", /obj/item/clothing/mask/bandana/striped/vampire, 10),
		new /datum/data/vending_product("Бандана с черепом", /obj/item/clothing/mask/bandana/skull/vampire, 10),
		new /datum/data/vending_product("Маска медведя", /obj/item/clothing/mask/animal/small/bear, 13),
		new /datum/data/vending_product("Маска крысы", /obj/item/clothing/mask/animal/small/rat, 10),
		new /datum/data/vending_product("Маска пчелы", /obj/item/clothing/mask/animal/small/bee, 12),
		new /datum/data/vending_product("Маска лисы", /obj/item/clothing/mask/animal/small/fox, 10),
		new /datum/data/vending_product("Маска летучей мыши", /obj/item/clothing/mask/animal/small/bat, 15),
		new /datum/data/vending_product("Маска ворона", /obj/item/clothing/mask/animal/small/raven, 20),
		new /datum/data/vending_product("Маска шакала", /obj/item/clothing/mask/animal/small/jackal, 20),
		new /datum/data/vending_product("Медицинская маска", /obj/item/clothing/mask/surgical, 10),
		new /datum/data/vending_product("Маска мумии", /obj/item/clothing/mask/mummy, 15),
		new /datum/data/vending_product("Маска пугала", /obj/item/clothing/mask/scarecrow, 10),
		new /datum/data/vending_product("Респиратор", /obj/item/clothing/mask/gas/vampire),
		new /datum/data/vending_product("Чёрно-золотая маска лучадора", /obj/item/clothing/mask/luchador, 10),
		new /datum/data/vending_product("Зелёная маска лучадора", /obj/item/clothing/mask/luchador/tecnicos, 10),
		new /datum/data/vending_product("Красно-синяя маска лучадора", /obj/item/clothing/mask/luchador/rudos, 10),
		new /datum/data/vending_product("Венецианская маска", /obj/item/clothing/mask/vampire/venetian_mask, 30),
		new /datum/data/vending_product("Роскошная венецианская маска", /obj/item/clothing/mask/vampire/venetian_mask/fancy, 200),
		new /datum/data/vending_product("Маска шута", /obj/item/clothing/mask/vampire/venetian_mask/jester, 50),
		new /datum/data/vending_product("Окровавленная маска", /obj/item/clothing/mask/vampire/venetian_mask/scary, 30),
		new /datum/data/vending_product("Маска комедии", /obj/item/clothing/mask/vampire/comedy, 25),
		new /datum/data/vending_product("Маска трагедии", /obj/item/clothing/mask/vampire/tragedy, 25),
		new /datum/data/vending_product("Шемаг", /obj/item/clothing/mask/vampire/shemagh, 20),
		new /datum/data/vending_product("Готический крест", /obj/item/card/hunter/gothic, 20),
	)
