/obj/structure/retail/flower_shop
	desc = "Единственный круглосуточный цветочный во всём Сан-Франциско."
	products_list = list(
		new /datum/data/vending_product("Садовые перчатки", /obj/item/clothing/gloves/botanic_leather, 45),
		new /datum/data/vending_product("Респиратор", /obj/item/clothing/mask/gas/vampire),
		new /datum/data/vending_product("Сумка для растений", /obj/item/storage/bag/plants, 45),
		new /datum/data/vending_product("Обычное удобрение", /obj/item/reagent_containers/cup/bottle/nutrient/ez, 100),
		new /datum/data/vending_product("Гербицид", /obj/item/reagent_containers/spray/weedspray, 25),
		new /datum/data/vending_product("Пестицид", /obj/item/reagent_containers/spray/pestspray, 25),
		new /datum/data/vending_product("Садовая лопатка", /obj/item/shovel/spade, 100),
		new /datum/data/vending_product("Деревянное ведро", /obj/item/reagent_containers/cup/bucket/wooden, 100),
		new /datum/data/vending_product("Секатор", /obj/item/secateurs, 100),
		new /datum/data/vending_product("Садовые грабли", /obj/item/cultivator/rake, 100),
		new /datum/data/vending_product("Культиватор", /obj/item/cultivator, 100),
		new /datum/data/vending_product("Семена мака", /obj/item/seeds/poppy, 50),
		new /datum/data/vending_product("Семена подсолнуха", /obj/item/seeds/sunflower, 50),
		new /datum/data/vending_product("Семена герани", /obj/item/seeds/poppy/geranium, 50),
		new /datum/data/vending_product("Семена лилии", /obj/item/seeds/poppy/lily, 50),
		//new /datum/data/vending_product("Forget me not seeds", /obj/item/seeds/forgetmenot, 50),
		new /datum/data/vending_product("Семена алоэ", /obj/item/seeds/aloe, 50),
		new /datum/data/vending_product("Семена яблони", /obj/item/seeds/apple, 50),
		new /datum/data/vending_product("Семена капусты", /obj/item/seeds/cabbage, 50),
		new /datum/data/vending_product("Семена моркови", /obj/item/seeds/carrot, 50),
		new /datum/data/vending_product("Семена кукурузы", /obj/item/seeds/corn, 50),
		new /datum/data/vending_product("Семена овса", /obj/item/seeds/wheat/oat, 50),
		new /datum/data/vending_product("Семена лука", /obj/item/seeds/onion, 50),
		new /datum/data/vending_product("Семена пастернака", /obj/item/seeds/carrot/parsnip, 50),
		new /datum/data/vending_product("Семена гороха", /obj/item/seeds/peas, 50),
		new /datum/data/vending_product("Семенной картофель", /obj/item/seeds/potato, 50),
		new /datum/data/vending_product("Семена тыквы", /obj/item/seeds/pumpkin, 50),
		new /datum/data/vending_product("Семена риса", /obj/item/seeds/wheat/rice, 50),
		new /datum/data/vending_product("Семена сои", /obj/item/seeds/soya, 50),
		new /datum/data/vending_product("Семена томата", /obj/item/seeds/tomato, 50),
		new /datum/data/vending_product("Бочка для брожения", /obj/structure/fermenting_barrel, 230),
		new /datum/data/vending_product("Мешок грунта", /obj/item/soil_sack),
		new /datum/data/vending_product("Мешок плодородного грунта", /obj/item/soil_sack/rich),
		)
