/obj/structure/retail/grocery_store
	desc = "Небольшой продуктовый магазин."
	products_list = list(
		new /datum/data/vending_product("Шоколадный батончик", /obj/item/food/chocolatebar),
		new /datum/data/vending_product("Чипсы", /obj/item/food/chips),
		new /datum/data/vending_product("Бутылка воды", /obj/item/reagent_containers/cup/glass/vampirewater),
		new /datum/data/vending_product("Банка содовой", /obj/item/reagent_containers/cup/soda_cans/vampiresoda),
		new /datum/data/vending_product("Двухлитровая бутылка колы", /obj/item/reagent_containers/cup/glass/vampirecola),
		new /datum/data/vending_product("Банка колы", /obj/item/reagent_containers/cup/soda_cans/vampirecola),
		new /datum/data/vending_product("Газировка Summer Thaw", /obj/item/reagent_containers/cup/soda_cans/summer_thaw),
		new /datum/data/vending_product("Молоко", /obj/item/reagent_containers/condiment/milk),
		new /datum/data/vending_product("Хлеб", /obj/item/food/bread/plain, 8),
		new /datum/data/vending_product("Спагетти", /obj/item/food/spaghetti/raw, 6),
		new /datum/data/vending_product("Помидор", /obj/item/food/grown/tomato),
		new /datum/data/vending_product("Капуста", /obj/item/food/grown/cabbage),
		new /datum/data/vending_product("Чеснок", /obj/item/food/grown/garlic),
		new /datum/data/vending_product("Лук", /obj/item/food/grown/onion),
		new /datum/data/vending_product("Пастернак", /obj/item/food/grown/carrotlike/parsnip),
		new /datum/data/vending_product("Горох", /obj/item/food/grown/peas),
		new /datum/data/vending_product("Кукуруза", /obj/item/food/grown/corn),
		new /datum/data/vending_product("Яблоко", /obj/item/food/grown/apple),
		new /datum/data/vending_product("Ягоды", /obj/item/food/grown/berries),
		new /datum/data/vending_product("Банан", /obj/item/food/grown/banana),
		new /datum/data/vending_product("Кулинарный фермент", /obj/item/reagent_containers/condiment/enzyme, 12),
		new /datum/data/vending_product("Солонка", /obj/item/reagent_containers/condiment/saltshaker, 3),
		new /datum/data/vending_product("Мельница для перца", /obj/item/reagent_containers/condiment/peppermill, 3),
		new /datum/data/vending_product("Соус барбекю", /obj/item/reagent_containers/condiment/bbqsauce, 3),
		new /datum/data/vending_product("Соевый соус", /obj/item/reagent_containers/condiment/soysauce, 4),
		new /datum/data/vending_product("Майонез", /obj/item/reagent_containers/condiment/mayonnaise, 3),
		new /datum/data/vending_product("Упаковка яиц", /obj/item/storage/fancy/egg_box),
		new /datum/data/vending_product("Сливки", /obj/item/reagent_containers/cup/glass/bottle/juice/cream),
		new /datum/data/vending_product("Йогурт", /obj/item/reagent_containers/condiment/yoghurt),
		new /datum/data/vending_product("Уксус", /obj/item/reagent_containers/condiment/vinegar),
		new /datum/data/vending_product("Растительное масло", /obj/item/reagent_containers/condiment/vegetable_oil),
		new /datum/data/vending_product("Оливковое масло", /obj/item/reagent_containers/condiment/olive_oil),
		new /datum/data/vending_product("Арахисовая паста", /obj/item/reagent_containers/condiment/peanut_butter),
		new /datum/data/vending_product("Вишнёвый джем", /obj/item/reagent_containers/condiment/cherryjelly),
		new /datum/data/vending_product("Мёд", /obj/item/reagent_containers/condiment/honey),
		new /datum/data/vending_product("Пакет муки", /obj/item/reagent_containers/condiment/flour, 3),
		new /datum/data/vending_product("Пакет сахара", /obj/item/reagent_containers/condiment/sugar),
		new /datum/data/vending_product("Пакет риса", /obj/item/reagent_containers/condiment/rice, 3),
		new /datum/data/vending_product("Кукурузная мука", /obj/item/reagent_containers/condiment/cornmeal),
		new /datum/data/vending_product("Бутылка пива", /obj/item/reagent_containers/cup/glass/bottle/beer/vampire),
		new /datum/data/vending_product("Пиво Blue Stripe", /obj/item/reagent_containers/cup/glass/bottle/beer/vampire/blue_stripe),
		new /datum/data/vending_product("Упаковка свечей", /obj/item/storage/fancy/candle_box),
		new /datum/data/vending_product("Набор от ушибов", /obj/item/stack/medical/bruise_pack),
		new /datum/data/vending_product("Кухонный нож", /obj/item/knife, 26),
		new /datum/data/vending_product("Скалка", /obj/item/kitchen/rollingpin, 8),
		new /datum/data/vending_product("Миска для замеса", /obj/item/reagent_containers/cup/mixing_bowl),
// CRIMSON EDIT ADD START - Shop Inventories Additions
		new /datum/data/vending_product("Картофель", /obj/item/food/grown/potato),
		new /datum/data/vending_product("Морковь", /obj/item/food/grown/carrotlike/carrot),
		new /datum/data/vending_product("Гриб", /obj/item/food/grown/mushroom),
		new /datum/data/vending_product("Тыква", /obj/item/food/grown/pumpkin),
		new /datum/data/vending_product("Баклажан", /obj/item/food/grown/eggplant),
		new /datum/data/vending_product("Соевые бобы", /obj/item/food/grown/soybeans),
		new /datum/data/vending_product("Перец чили", /obj/item/food/grown/chili),
		new /datum/data/vending_product("Кетчуп", /obj/item/reagent_containers/condiment/ketchup, 3),
		new /datum/data/vending_product("Горчица", /obj/item/reagent_containers/condiment/mustard, 3),
		new /datum/data/vending_product("Соевое молоко", /obj/item/reagent_containers/condiment/soymilk),
		new /datum/data/vending_product("Кусок сыра", /obj/item/food/cheese/wedge, 6),
// CRIMSON EDIT ADD END - Shop Inventories Additions
	)

/obj/structure/retail/deli
	desc = "Мясо и сыр!"
	products_list = list(
		new /datum/data/vending_product("Говяжья вырезка", /obj/item/food/meat/slab, 4),
		new /datum/data/vending_product("Отбивная", /obj/item/food/meat/rawcutlet, 1),
		new /datum/data/vending_product("Бекон", /obj/item/food/meat/rawbacon, 1),
		new /datum/data/vending_product("Фрикаделька", /obj/item/food/raw_meatball, 1),
		new /datum/data/vending_product("Котлета для бургера", /obj/item/food/raw_patty, 1),
		new /datum/data/vending_product("Колбаска", /obj/item/food/raw_sausage, 1),
		new /datum/data/vending_product("Салями", /obj/item/food/salami, 1),
		new /datum/data/vending_product("Куриная грудка", /obj/item/food/meat/slab/chicken, 3),
		new /datum/data/vending_product("Рыбное филе", /obj/item/food/fishmeat, 3),
		new /datum/data/vending_product("Головка сыра", /obj/item/food/cheese/wheel, 12),
		new /datum/data/vending_product("Сэндвич", /obj/item/food/sandwich, 3),
// CRIMSON EDIT ADD START - Shop Inventories Additions
		new /datum/data/vending_product("Сырая свинина", /obj/item/food/meat/slab/pig, 3),
		new /datum/data/vending_product("Сырой мясной рулет", /obj/item/food/raw_meatloaf, 4),
// CRIMSON EDIT ADD END - Shop Inventories Additions
	)
