/obj/structure/retail/hot_ishu
	products_list = list(
		new /datum/data/vending_product("\"Ваза\"", /obj/item/bong, 50),
		new /datum/data/vending_product("Крест", /obj/item/card/hunter, 25),
		new /datum/data/vending_product("Рюкзак", /obj/item/storage/backpack, 100),
		new /datum/data/vending_product("Чёрный гранжевый наряд", /obj/item/clothing/under/vampire/black, 20),
		new /datum/data/vending_product("Наряд для бурлеска", /obj/item/clothing/under/vampire/burlesque, 15),
		new /datum/data/vending_product("Женский латексный костюм", /obj/item/clothing/under/vampire/nosferatu/female, 15),
		new /datum/data/vending_product("Женский панк-наряд", /obj/item/clothing/under/vampire/brujah/female, 20),
		new /datum/data/vending_product("Латексный костюм", /obj/item/clothing/under/vampire/nosferatu, 15),
		new /datum/data/vending_product("Готическая одежда", /obj/item/clothing/under/vampire/gothic, 20),
		new /datum/data/vending_product("Готический наряд", /obj/item/clothing/under/vampire/brujah, 20),
		new /datum/data/vending_product("Замызганные штаны", /obj/item/clothing/under/vampire/malkavian, 20),
		new /datum/data/vending_product("Модный наряд", /obj/item/clothing/under/vampire/scenepink, 20),
		new /datum/data/vending_product("Мрачный наряд", /obj/item/clothing/under/vampire/scenemoody, 20),
		new /datum/data/vending_product("Наряд Пима", /obj/item/clothing/under/vampire/scenezim, 20),
		new /datum/data/vending_product("Откровенный наряд", /obj/item/clothing/under/vampire/sceneleopard, 20),
		new /datum/data/vending_product("Толстовка", /obj/item/clothing/suit/hooded/hoodie, 15),
		new /datum/data/vending_product("Толстовка \"Захватчик Пим\"", /obj/item/clothing/suit/hooded/hoodie/hoodie_pim, 20),
		new /datum/data/vending_product("Леопардовая шуба", /obj/item/clothing/suit/vampire/coat/leopard, 35),
		new /datum/data/vending_product("Куртка", /obj/item/clothing/suit/vampire/jacket, 15),
		new /datum/data/vending_product("Странный наряд готичной школьницы", /obj/item/clothing/under/vampire/malkavian/female, 20),
		new /datum/data/vending_product("Рубашка с пентаграммой", /obj/item/clothing/under/vampire/baali, 20),
		new /datum/data/vending_product("Юбка с пентаграммой", /obj/item/clothing/under/vampire/baali/female, 20),
		new /datum/data/vending_product("Панк-наряд", /obj/item/clothing/under/vampire/emo, 20),
		new /datum/data/vending_product("Красный хипстерский наряд", /obj/item/clothing/under/vampire/red, 20),
		new /datum/data/vending_product("Чёрные меховые сапоги", /obj/item/clothing/shoes/vampire/blackfur, 35),
		new /datum/data/vending_product("Коричневые меховые сапоги", /obj/item/clothing/shoes/vampire/brownfur, 35),
		new /datum/data/vending_product("Кеды до колена", /obj/item/clothing/shoes/vampire/pumped, 35),
// CRIMSON EDIT ADD START - Shop Inventories Additions
		new /datum/data/vending_product("Бумажник", /obj/item/storage/wallet/darkpack, 25),
		new /datum/data/vending_product("Ткань", /obj/item/stack/sheet/cloth, 5),
// CRIMSON EDIT ADD END - Shop Inventories Additions
	)
