/mob/living/carbon/human/proc/blood_bond(mob/living/carbon/human/regnant)
	if(HAS_TRAIT(src, TRAIT_UNBONDABLE) || HAS_TRAIT(regnant, TRAIT_DEFICIENT_VITAE))
		regnant.visible_message("[capitalize(regnant.declent_ru(NOMINATIVE))] вливает кровь в рот [declent_ru(DATIVE)]!", "Вы напоили [declent_ru(ACCUSATIVE)] своей витэ.")
		to_chat(src, span_warning("Эта <b>КРОВЬ</b> пьянит... но к тому, кто её дал, вы не чувствуете ничего."))
		message_admins("[ADMIN_LOOKUPFLW(regnant)] has attempted to bloodbond [ADMIN_LOOKUPFLW(src)] (UNBONDABLE/UNBONDING).")
		log_game("[key_name(regnant)] has attempted to bloodbond [key_name(src)] (UNBONDABLE/UNBONDING).")
	else
		apply_status_effect(/datum/status_effect/blood_bond, regnant)
		regnant.visible_message("[capitalize(regnant.declent_ru(NOMINATIVE))] вливает кровь в рот [declent_ru(DATIVE)]!", "Вы напоили [declent_ru(ACCUSATIVE)] своей витэ.")
		to_chat(src, span_warning("Эта <b>КРОВЬ</b> пьянит..."))
		message_admins("[ADMIN_LOOKUPFLW(regnant)] has bloodbonded [ADMIN_LOOKUPFLW(src)].")
		log_game("[key_name(regnant)] has bloodbonded [key_name(src)].")
