export const JOBS_RU = {
  Assistant: 'Ассистент',
  Prisoner: 'Заключённый',
  Captain: 'Капитан',
  'Head of Personnel': 'Глава персонала',
  'Head of Security': 'Глава службы безопасности',
  'Research Director': 'Директор исследований',
  'Chief Engineer': 'Главный инженер',
  'Chief Medical Officer': 'Главный врач',
  AI: 'ИИ',
  Cyborg: 'Киборг',
  'Personal AI': 'Персональный ИИ',
  'Human AI': 'Большой брат',
  Warden: 'Смотритель',
  Detective: 'Детектив',
  'Security Officer': 'Офицер',
  'Security Officer (Cargo)': 'Офицер (Снабжение)',
  'Security Officer (Engineering)': 'Офицер (Инженерия)',
  'Security Officer (Medical)': 'Офицер (Медицина)',
  'Security Officer (Science)': 'Офицер (Исследование)',
  'Station Engineer': 'Станционный инженер',
  'Atmospheric Technician': 'Атмосферный техник',
  Coroner: 'Коронер',
  'Medical Doctor': 'Врач',
  Paramedic: 'Парамедик',
  Chemist: 'Химик',
  Scientist: 'Ученый',
  Roboticist: 'Робототехник',
  Geneticist: 'Генетик',
  Quartermaster: 'Квартирмейстер',
  'Cargo Technician': 'Грузчик',
  'Shaft Miner': 'Шахтер',
  Bitrunner: 'Битраннер',
  Bartender: 'Бармен',
  Botanist: 'Ботаник',
  Cook: 'Повар',
  Chef: 'Шеф',
  Janitor: 'Уборщик',
  Clown: 'Клоун',
  Mime: 'Мим',
  Curator: 'Куратор',
  Lawyer: 'Юрист',
  Chaplain: 'Священник',
  Psychologist: 'Психолог',
  // Event jobs
  'Veteran Security Advisor': 'Ветеран советчик СБ',
  'Bridge Assistant': 'Адъютант',
  // City
  Citizen: 'Горожанин',
  Unassigned: 'Без должности',
  'Street Janitor': 'Дворник',
  'Taxi Driver': 'Таксист',
  'Red News Reporter': 'Репортёр RED News',
  Priest: 'Священник',
  'Club Worker': 'Работник клуба',
  // Camarilla
  Prince: 'Принц',
  Seneschal: 'Сенешаль',
  Sheriff: 'Шериф',
  Harpy: 'Гарпия',
  Hound: 'Пёс',
  'Tower Employee': 'Сотрудник Башни',
  'Primogen Toreador': 'Примоген клана Тореадор',
  'Primogen Banu Haqim': 'Примоген клана Бану Хаким',
  'Primogen Lasombra': 'Примоген клана Ласомбра',
  'Primogen Malkavian': 'Примоген клана Малкавиан',
  'Primogen Nosferatu': 'Примоген клана Носферату',
  'Primogen Ventrue': 'Примоген клана Вентру',
  'Primogen Brujah': 'Примоген клана Бруха',
  // Anarchs
  Baron: 'Барон',
  Emissary: 'Эмиссар',
  Sweeper: 'Дозорный',
  Bruiser: 'Громила',
  Tapster: 'Трактирщик',
  // Chantry
  'Chantry Regent': 'Регент капеллы',
  'Chantry Archivist': 'Архивариус капеллы',
  'Chantry Gargoyle': 'Горгулья капеллы',
  // Manor
  Voivode: 'Воевода',
  Bogatyr: 'Богатырь',
  Zadruga: 'Задруга',
  // Giovanni
  Capo: 'Капо',
  'I Nonni': 'И Нонни',
  'La Squadra': 'Ла Скуадра',
  'La Famiglia': 'Ла Фамилья',
  // Sabbat
  'Sabbat Ductus': 'Дуктус Шабаша',
  'Sabbat Priest': 'Духовник Шабаша',
  'Sabbat Pack': 'Член стаи Шабаша',
  // Police
  'Police Captain': 'Капитан полиции',
  'Police Sergeant': 'Сержант полиции',
  'Police Officer': 'Полицейский',
  'Emergency Dispatcher': 'Диспетчер экстренных служб',
  'Federal Investigator': 'Федеральный агент',
  // Clinic
  'Clinic Director': 'Директор клиники',
  Doctor: 'Доктор',
  'Clinic Guard': 'Охранник клиники',
  // Warehouse
  Dealer: 'Делец',
  'Supply Technician': 'Кладовщик',
  // Garou Nation
  Councillor: 'Советник',
  Truthcatcher: 'Ловец Истины',
  Warder: 'Страж',
  Wyrmfoe: 'Враг Вирма',
  Guardian: 'Защитник',
  'Sept Keeper': 'Хранитель септа',
  // Pentex
  'Branch Lead': 'Глава филиала',
  Executive: 'Руководитель',
  'Internal Affairs Agent': 'Агент внутренних расследований',
  'Chief of Security': 'Начальник службы безопасности',
  'Security Agent': 'Агент службы безопасности',
  Employee: 'Сотрудник',
  // Society of Leopold
  Abbe: 'Аббат',
  Inquisitor: 'Инквизитор',
  Condottieri: 'Кондотьер',
  Novice: 'Послушник',
  // Triad
  'Mountain Master': 'Хозяин Горы',
  'Deputy Mountain Master': 'Заместитель Хозяина Горы',
  'Red Pole': 'Красный Шест',
  'Blue Lanterns': 'Синий Фонарь',
  // Alternative titles
  'Private Investigator': 'Частный детектив',
  'Private Security': 'Частный охранник',
  Tourist: 'Турист',
  Visitor: 'Приезжий',
  Entertainer: 'Артист',
  Entrepreneur: 'Предприниматель',
  Contractor: 'Подрядчик',
  Fixer: 'Решала',
  Attorney: 'Адвокат',
  Paralegal: 'Помощник юриста',
  'Red News Cameraman': 'Оператор RED News',
  'Red News Talking Head': 'Говорящая голова RED News',
  'Red News Infomercial Salesperson': 'Ведущий телемагазина RED News',
  'Red News Entertainment Host': 'Ведущий развлекательного шоу RED News',
  'Red News Late Night Talkshow Host': 'Ведущий ночного ток-шоу RED News',
  Nun: 'Монахиня',
  Mother: 'Матушка',
  Father: 'Святой отец',
  Imam: 'Имам',
  Monk: 'Монах',
  Reverend: 'Преподобный',
  Preacher: 'Проповедник',
  Rabbi: 'Раввин',
  Stripper: 'Артист стриптиза',
  'Club Bouncer': 'Вышибала клуба',
  'Club Bartender': 'Бармен клуба',
  'Club Attendant': 'Служащий клуба',
  'Tower Cleaner': 'Уборщик Башни',
  'Tower Assistant': 'Ассистент Башни',
  'Tower Security Guard': 'Охранник Башни',
  'Tower Personal Driver': 'Личный водитель при Башне',
  'Tower Personal Attendant': 'Личный помощник при Башне',
  Bouncer: 'Вышибала',
  Coyote: 'Койот',
  Piper: 'Дудочник',
  'Rotten Apple': 'Гнилое Яблоко',
  Houdini: 'Гудини',
  Prospect: 'Проспект',
  Cleaver: 'Тесак',
  Molotov: 'Молотов',
  Barkeeper: 'Кабатчик',
  Server: 'Разносчик',
  'Soda Jerk': 'Газировщик',
  Waiter: 'Официант',
  Waitress: 'Официантка',
  'Police Cadet': 'Курсант полиции',
  'Senior Police Officer': 'Старший полицейский',
  'Police Supervisor': 'Начальник смены',
  'Training Officer': 'Офицер-наставник',
  'SAD Officer': 'Сотрудник Отдела особых дел',
  'Project Twilight Operative': 'Оперативник проекта "Сумерки"',
  'FIRSTLIGHT Analyst': 'Аналитик FIRSTLIGHT',
  'Medical Student': 'Студент-медик',
  Intern: 'Интерн',
  Nurse: 'Медсестра',
  Resident: 'Ординатор',
  'General Practitioner': 'Терапевт',
  Surgeon: 'Хирург',
  Physician: 'Лечащий врач',
  EMT: 'Фельдшер скорой',
  'Clinic Orderly': 'Санитар клиники',
  'Hospise Orderly': 'Санитар хосписа',
  'Endron Branch Lead': 'Глава филиала "Эндрон"',
  'Endron Branch Director': 'Директор филиала "Эндрон"',
  'Endron Regional Director': 'Региональный директор "Эндрон"',
  'Endron Operations Director': 'Операционный директор "Эндрон"',
  'Endron Executive': 'Руководитель "Эндрон"',
  'Endron Regional Manager': 'Региональный менеджер "Эндрон"',
  'Endron Manager': 'Менеджер "Эндрон"',
  'Endron Marketing Director': 'Директор по маркетингу "Эндрон"',
  'Endron Public Relations Manager': 'Менеджер по связям с общественностью "Эндрон"',
  'Endron Deputy Branch Director': 'Заместитель директора филиала "Эндрон"',
  'Endron Chief Innovation Officer': 'Директор по инновациям "Эндрон"',
  'Endron Chief Science Officer': 'Директор по науке "Эндрон"',
  'Endron Chief Financial Officer': 'Финансовый директор "Эндрон"',
  'Endron Employee': 'Сотрудник "Эндрон"',
  'Endron Janitor': 'Уборщик "Эндрон"',
  'Endron Secretary': 'Секретарь "Эндрон"',
  'Endron Researcher': 'Исследователь "Эндрон"',
  'Endron Labourer': 'Рабочий "Эндрон"',
};

const REVERSED_JOBS_RU = Object.entries(JOBS_RU).reduce(
  (reversed_jobs, [key, value]) => {
    reversed_jobs[value] = key;
    return reversed_jobs;
  },
  {},
);

export function ReverseJobsRu(value: string) {
  return REVERSED_JOBS_RU[value] || value;
}

export const DEPARTMENTS_RU = {
  Command: 'Командование',
  Security: 'Безопасность',
  Service: 'Обслуживание',
  Cargo: 'Снабжение',
  Science: 'Исследование',
  Medical: 'Медицина',
  Silicon: 'Синтетики',
  Engineering: 'Инженерия',
  'No Department': 'Без отдела',
  Citizen: 'Горожане',
  Prince: 'Принц',
  Camarilla: 'Камарилья',
  Church: 'Церковь',
  Clinic: 'Клиника',
  Anarch: 'Анархи',
  'Strip Club': 'Стрип-клуб',
  Warehouse: 'Склад',
  Giovanni: 'Джованни',
  Police: 'Полиция',
  Sabbat: 'Шабаш',
  Chantry: 'Капелла',
  Manor: 'Поместье',
  'City Services': 'Городские службы',
  Pentex: 'Пентекс',
  'Garou Nation': 'Нация Гару',
  'Society of Leopold': 'Общество Леопольда',
  'Chinese Triad': 'Китайская триада',
};

export const EXP_TYPES_RU = {
  Living: 'Живые персонажи',
  Crew: 'Любая должность',
  Command: 'Командование',
  Engineering: 'Инженерия',
  Medical: 'Медицина',
  Science: 'Исследование',
  Supply: 'Склад',
  Security: 'Безопасность',
  Silicon: 'Синтетики',
  Service: 'Обслуживание',
  Antag: 'Антагонисты',
  Special: 'Особые роли',
  Ghost: 'Призрак',
  Admin: 'Администратор',
  Playtime: 'Общее время игры',
  'Garou Nation': 'Нация Гару',
  Pentex: 'Пентекс',
  'Camarilla Authorities': 'Власти Камарильи',
  Chantry: 'Капелла',
  Anarchs: 'Анархи',
  Sabbat: 'Шабаш',
  'Police Force': 'Полиция',
  'City Services': 'Городские службы',
  Clinic: 'Клиника',
  'Giovanni Family': 'Семья Джованни',
  'Tzimisce Manor': 'Поместье Цимисхов',
  Church: 'Церковь',
  'Strip Club': 'Стрип-клуб',
  'Society of Leopold': 'Общество Леопольда',
  'Chinese Triad': 'Китайская триада',
};
