/datum/preference/choiced/adjective_preference
	category = PREFERENCE_CATEGORY_NON_CONTEXTUAL
	priority = PREFERENCE_PRIORITY_TABLETOP
	savefile_key = "adjective_preference"
	savefile_identifier = PREFERENCE_CHARACTER
	main_feature_name = "Прилагательное"
	can_randomize = TRUE

/datum/preference/choiced/adjective_preference/init_possible_values()
	return assoc_to_keys(GLOB.preference_adjectives)

/datum/preference/choiced/adjective_preference/create_default_value()
	return pick(assoc_to_keys(GLOB.preference_adjectives))

/datum/preference/choiced/adjective_preference/apply_to_human(mob/living/carbon/human/target, value, datum/preferences/preferences)
	target.visible_adjective = value
	target.update_visible_name()

/datum/preference/choiced/adjective_preference/compile_constant_data()
	var/list/data = ..()
	var/list/display_names = list()
	for(var/adjective in GLOB.preference_adjectives_ru)
		display_names[adjective] = capitalize(GLOB.preference_adjectives_ru[adjective][1])
	data[CHOICED_PREFERENCE_DISPLAY_NAMES] = display_names
	return data

/// Saved adjective -> list(masculine, feminine) shown to players
GLOBAL_LIST_INIT(preference_adjectives_ru, list(
	"Addled" = list("одурманенный", "одурманенная"),
	"Aimless" = list("неприкаянный", "неприкаянная"),
	"Angsty" = list("издёрганный", "издёрганная"),
	"Awkward" = list("неловкий", "неловкая"),
	"Bedraggled" = list("растрёпанный", "растрёпанная"),
	"Blemished" = list("рябой", "рябая"),
	"Bony" = list("костлявый", "костлявая"),
	"Brawny" = list("дюжий", "дюжая"),
	"Breathtaking" = list("сногсшибательный", "сногсшибательная"),
	"Brutish" = list("звероватый", "звероватая"),
	"Bruised" = list("побитый", "побитая"),
	"Bubbly" = list("жизнерадостный", "жизнерадостная"),
	"Bulky" = list("массивный", "массивная"),
	"Burly" = list("здоровенный", "здоровенная"),
	"Calm" = list("спокойный", "спокойная"),
	"Chaotic" = list("суматошный", "суматошная"),
	"Charming" = list("обаятельный", "обаятельная"),
	"Chubby" = list("пухлый", "пухлая"),
	"Coarse" = list("грубый", "грубая"),
	"Confident" = list("уверенный", "уверенная"),
	"Creepy" = list("жуткий", "жуткая"),
	"Curvy" = list("фигуристый", "фигуристая"),
	"Dastardly" = list("подлый", "подлая"),
	"Deformed" = list("изуродованный", "изуродованная"),
	"Delicate" = list("нежный", "нежная"),
	"Despondent" = list("унылый", "унылая"),
	"Dignified" = list("величавый", "величавая"),
	"Difficult" = list("несносный", "несносная"),
	"Disgusting" = list("отвратительный", "отвратительная"),
	"Disturbing" = list("пугающий", "пугающая"),
	"Dull" = list("скучный", "скучная"),
	"Effeminate" = list("женоподобный", "женоподобная"),
	"Elegant" = list("элегантный", "элегантная"),
	"Emaciated" = list("измождённый", "измождённая"),
	"Energetic" = list("энергичный", "энергичная"),
	"Exasperated" = list("раздражённый", "раздражённая"),
	"Exotic" = list("экзотичный", "экзотичная"),
	"Faint" = list("слабый", "слабая"),
	"Feisty" = list("задиристый", "задиристая"),
	"Feral" = list("дикий", "дикая"),
	"Flabby" = list("дряблый", "дряблая"),
	"Flamboyant" = list("эпатажный", "эпатажная"),
	"Fragile" = list("хрупкий", "хрупкая"),
	"Frail" = list("хилый", "хилая"),
	"Frazzled" = list("замотанный", "замотанная"),
	"Friendly" = list("дружелюбный", "дружелюбная"),
	"Gangly" = list("долговязый", "долговязая"),
	"Gap-toothed" = list("щербатый", "щербатая"),
	"Gaunt" = list("осунувшийся", "осунувшаяся"),
	"Gawping" = list("глазеющий", "глазеющая"),
	"Gentle" = list("кроткий", "кроткая"),
	"Gloomy" = list("мрачный", "мрачная"),
	"Gormless" = list("бестолковый", "бестолковая"),
	"Hawkish" = list("хищный", "хищная"),
	"Healthy" = list("здоровый", "здоровая"),
	"Hefty" = list("грузный", "грузная"),
	"Hobbling" = list("прихрамывающий", "прихрамывающая"),
	"Hyper" = list("гиперактивный", "гиперактивная"),
	"Imposing" = list("внушительный", "внушительная"),
	"Inscrutable" = list("непроницаемый", "непроницаемая"),
	"Jaded" = list("пресыщенный", "пресыщенная"),
	"Lax" = list("расслабленный", "расслабленная"),
	"Lean" = list("поджарый", "поджарая"),
	"Limp" = list("вялый", "вялая"),
	"Lithe" = list("гибкий", "гибкая"),
	"Lopsided" = list("кособокий", "кособокая"),
	"Lovely" = list("прелестный", "прелестная"),
	"Malnourished" = list("недокормленный", "недокормленная"),
	"Malodorous" = list("зловонный", "зловонная"),
	"Mangled" = list("искалеченный", "искалеченная"),
	"Manic" = list("маниакальный", "маниакальная"),
	"Masculine" = list("мужественный", "мужественная"),
	"Messy" = list("неряшливый", "неряшливая"),
	"Muscular" = list("мускулистый", "мускулистая"),
	"Nervous" = list("нервный", "нервная"),
	"Nimble" = list("проворный", "проворная"),
	"Oily" = list("сальный", "сальная"),
	"Pathetic" = list("жалкий", "жалкая"),
	"Pensive" = list("задумчивый", "задумчивая"),
	"Peppy" = list("бодрый", "бодрая"),
	"Petite" = list("миниатюрный", "миниатюрная"),
	"Petulant" = list("капризный", "капризная"),
	"Pompous" = list("напыщенный", "напыщенная"),
	"Pugnacious" = list("драчливый", "драчливая"),
	"Quievering" = list("дрожащий", "дрожащая"),
	"Radical" = list("отвязный", "отвязная"),
	"Repulsive" = list("омерзительный", "омерзительная"),
	"Robust" = list("крепкий", "крепкая"),
	"Roguish" = list("плутоватый", "плутоватая"),
	"Rotund" = list("тучный", "тучная"),
	"Rough" = list("неотёсанный", "неотёсанная"),
	"Round" = list("округлый", "округлая"),
	"Scarred" = list("покрытый шрамами", "покрытая шрамами"),
	"Scheming" = list("коварный", "коварная"),
	"Scrawny" = list("тощий", "тощая"),
	"Sculpted" = list("точёный", "точёная"),
	"Sensitive" = list("чувствительный", "чувствительная"),
	"Shifty" = list("изворотливый", "изворотливая"),
	"Shrewd" = list("проницательный", "проницательная"),
	"Sickly" = list("болезненный", "болезненная"),
	"Skinny" = list("худой", "худая"),
	"Skittish" = list("пугливый", "пугливая"),
	"Sleek" = list("холёный", "холёная"),
	"Sleepy" = list("сонный", "сонная"),
	"Slender" = list("стройный", "стройная"),
	"Slimy" = list("скользкий", "скользкая"),
	"Slovenly" = list("неопрятный", "неопрятная"),
	"Sluggish" = list("медлительный", "медлительная"),
	"Sly" = list("лукавый", "лукавая"),
	"Smooth" = list("лощёный", "лощёная"),
	"Sniveling" = list("хнычущий", "хнычущая"),
	"Soulrendered" = list("опустошённый", "опустошённая"),
	"Spacy" = list("рассеянный", "рассеянная"),
	"Stiff" = list("скованный", "скованная"),
	"Stony" = list("бесстрастный", "бесстрастная"),
	"Stout" = list("плотный", "плотная"),
	"Strapping" = list("рослый", "рослая"),
	"Sturdy" = list("коренастый", "коренастая"),
	"Stylish" = list("стильный", "стильная"),
	"Swarthy" = list("смуглый", "смуглая"),
	"Tense" = list("напряжённый", "напряжённая"),
	"Towering" = list("высоченный", "высоченная"),
	"Tubular" = list("бочкообразный", "бочкообразная"),
	"Twitchy" = list("дёрганый", "дёрганая"),
	"Unattractive" = list("непривлекательный", "непривлекательная"),
	"Unblemished" = list("безупречный", "безупречная"),
	"Unhealthy" = list("нездоровый", "нездоровая"),
	"Unremarkable" = list("неприметный", "неприметная"),
	"Unsightly" = list("неприглядный", "неприглядная"),
	"Unstable" = list("неуравновешенный", "неуравновешенная"),
	"Verbose" = list("многословный", "многословная"),
	"Vigilant" = list("бдительный", "бдительная"),
	"Vigorous" = list("неутомимый", "неутомимая"),
	"Waifish" = list("щуплый", "щуплая"),
	"Weary" = list("усталый", "усталая"),
	"Wilted" = list("увядший", "увядшая"),
	"Wily" = list("хитрый", "хитрая"),
	"Withered" = list("иссохший", "иссохшая"),
	"Worn-Out" = list("измотанный", "измотанная"),
	"Wrinkly" = list("морщинистый", "морщинистая"),
	"Zealous" = list("рьяный", "рьяная"),
	"Zesty" = list("задорный", "задорная"),
))
