const NOTIFICATION_SOUND_RU: Record<string, string> = {
  'Alert 1': 'Сигнал 1',
  'Alert 2': 'Сигнал 2',
  'Alert 3': 'Сигнал 3',
  'Alert 4': 'Сигнал 4',
  Bell: 'Колокольчик',
  Beep: 'Писк',
  BUZZ: 'Жужжание',
  'BYOND Pager': 'Пейджер BYOND',
  'BYOND Pager Down': 'Пейджер BYOND (низкий)',
  Bikehorn: 'Велосипедный клаксон',
  Chime: 'Перезвон',
  'Chord 1': 'Аккорд 1',
  'Chord 2': 'Аккорд 2',
  'Chord 3': 'Аккорд 3',
  Codec: 'Кодек',
  Ding: 'Дзынь',
  Grandma: 'Бабушка',
  Horn: 'Гудок',
  Maus: 'Маус',
  'Meow 1': 'Мяу 1',
  'Meow 2': 'Мяу 2',
  'Meow 3': 'Мяу 3',
  'Meow 4': 'Мяу 4',
  'Meow (Electric)': 'Мяу (электронное)',
  Morse: 'Морзянка',
  'Oh Hi Mark': 'О, привет, Марк',
  'Mysterious Jingle': 'Загадочная мелодия',
  Normalize: 'Нормализация',
  'Not Alphys': 'Не Альфис',
  'Phone Chime': 'Телефонный перезвон',
  Piano: 'Пианино',
  Ping: 'Пинг',
  Speaking: 'Голос',
  Splat: 'Шлепок',
  Target: 'Цель',
  'Terminal Notif 1': 'Уведомление терминала 1',
  Weh: 'Вэ',
};

export function notificationSoundLabel(sound: string): string {
  return NOTIFICATION_SOUND_RU[sound] || sound;
}
