import { Food } from '../PreferencesMenu/types';

export const TYPE_ICONS = {
  'Can Make': 'utensils',
  [Food.Alcohol]: 'wine-glass',
  [Food.Breakfast]: 'sun',
  [Food.Bugs]: 'bug',
  [Food.Cloth]: 'tshirt',
  [Food.Dairy]: 'cheese',
  [Food.Egg]: 'egg',
  [Food.Fried]: 'fire',
  [Food.Fruit]: 'apple-alt',
  [Food.Gore]: 'skull',
  [Food.Grain]: 'wheat-awn',
  [Food.Gross]: 'trash',
  [Food.Junkfood]: 'pizza-slice',
  [Food.Meat]: 'bacon',
  [Food.Nuts]: 'seedling',
  [Food.Oranges]: 'apple-alt',
  [Food.Pineapple]: 'apple-alt',
  [Food.Raw]: 'drumstick-bite',
  [Food.Seafood]: 'fish',
  [Food.Stone]: 'gem',
  [Food.Sugar]: 'candy-cane',
  [Food.Toxic]: 'biohazard',
  [Food.Vegetables]: 'carrot',
} as const;

export const CATEGORY_ICONS_CRAFTING = {
  'Can Make': 'hammer',
  'Weapons Melee': 'hand-fist',
  'Weapons Ranged': 'gun',
  'Weapon Ammo': 'box',
  Robotics: 'robot',
  Misc: 'shapes',
  Tribal: 'campground',
  Clothing: 'shirt',
  Drinks: 'wine-bottle',
  Chemistry: 'microscope',
  Atmospherics: 'fan',
  Structures: 'cube',
  Tiles: 'border-all',
  Windows: 'person-through-window',
  Doors: 'door-open',
  Furniture: 'chair',
  Equipment: 'calculator',
  Containers: 'briefcase',
  Tools: 'screwdriver-wrench',
  Entertainment: 'masks-theater',
  'Blood Cult': 'users',
  Construction: 'trowel-bricks',
} as const;

export const CATEGORY_ICONS_COOKING = {
  'Can Make': 'utensils',
  Appetizer: 'bread-slice',
  Bread: 'bread-slice',
  Burger: 'burger',
  Burrito: 'circle-o',
  Cake: 'cake-candles',
  Candy: 'candy-cane',
  Component: 'cubes',
  Cookie: 'cookie',
  Dessert: 'face-grin-beam-sweat',
  Frozen: 'ice-cream',
  Italian: 'pizza-slice',
  Japanese: 'earth-asia',
  Lizard: 'dragon',
  Martian: 'globe',
  Meat: 'bacon',
  Mexican: 'earth-americas',
  Mothic: 'shirt',
  Noodles: 'wheat-awn',
  Pastry: 'cookie',
  Pie: 'chart-pie',
  Pizza: 'pizza-slice',
  Rice: 'bowl-rice',
  Salad: 'leaf',
  Sandwich: 'hotdog',
  Soup: 'mug-hot',
  Sushi: 'fish',
  Taco: 'circle-o',
  Terran: 'earth-europe',
  Uncategorized: 'shapes',
  'Main Course': 'drumstick-bite',
  Breakfast: 'sun',
  Snack: 'compress',
  Condiment: 'bottle-water',
} as const;

const CRAFTING_LABELS_RU: Record<string, string> = {
  'Can Make': 'Можно сделать',
  Foods: 'Еда',
  Drinks: 'Напитки',
  'Weapons Melee': 'Холодное оружие',
  'Weapons Ranged': 'Стрелковое оружие',
  'Weapon Ammo': 'Боеприпасы',
  Weaponry: 'Оружие',
  Robotics: 'Робототехника',
  Misc: 'Разное',
  Tribal: 'Племенное',
  Clothing: 'Одежда',
  Chemistry: 'Химия',
  Atmospherics: 'Атмосфера',
  Structures: 'Постройки',
  Tiles: 'Плитка',
  Windows: 'Окна',
  Doors: 'Двери',
  Furniture: 'Мебель',
  Equipment: 'Оборудование',
  Containers: 'Ёмкости',
  Tools: 'Инструменты',
  Entertainment: 'Развлечения',
  'Blood Cult': 'Культ крови',
  Construction: 'Строительство',
  Tzimisce: 'Цимисхи',
  Appetizer: 'Закуски',
  Bread: 'Хлеб',
  Burger: 'Бургеры',
  Burrito: 'Буррито',
  Cake: 'Торты',
  Candy: 'Конфеты',
  Component: 'Заготовки',
  Cookie: 'Печенье',
  Dessert: 'Десерты',
  Frozen: 'Мороженое',
  Italian: 'Итальянская кухня',
  Japanese: 'Японская кухня',
  Lizard: 'Кухня ящеров',
  Martian: 'Марсианская кухня',
  Meat: 'Мясо',
  Mexican: 'Мексиканская кухня',
  Mothic: 'Кухня молей',
  Noodles: 'Лапша',
  Pastry: 'Выпечка',
  Pie: 'Пироги',
  Pizza: 'Пицца',
  Rice: 'Рис',
  Salad: 'Салаты',
  Sandwich: 'Сэндвичи',
  Soup: 'Супы',
  Sushi: 'Суши',
  Taco: 'Тако',
  Terran: 'Земная кухня',
  Uncategorized: 'Без категории',
  'Main Course': 'Основное блюдо',
  Breakfast: 'Завтрак',
  Snack: 'Перекус',
  Condiment: 'Приправы',
  ALCOHOL: 'Алкоголь',
  BREAKFAST: 'Завтрак',
  BUGS: 'Насекомые',
  CLOTH: 'Ткань',
  DAIRY: 'Молочное',
  FRIED: 'Жареное',
  FRUIT: 'Фрукты',
  GORE: 'Потроха',
  GRAIN: 'Злаки',
  GROSS: 'Гадость',
  JUNKFOOD: 'Фастфуд',
  MEAT: 'Мясо',
  NUTS: 'Орехи',
  ORANGES: 'Апельсины',
  PINEAPPLE: 'Ананасы',
  RAW: 'Сырое',
  SEAFOOD: 'Морепродукты',
  STONE: 'Камень',
  SUGAR: 'Сладкое',
  TOXIC: 'Ядовитое',
  VEGETABLES: 'Овощи',
  EGG: 'Яйца',
};

export function craftingLabel(key: string, fallback = key): string {
  return CRAFTING_LABELS_RU[key] || fallback;
}
